export const dummyData = [
  {
    client_id: "d26070cc",
    date_testing: "2018-05-10",
    date_birthdate: "1950-01-01",
    gender: 1,
    ethnicity: 5,
    creatine: 0.37,
    chloride: 80.65,
    fasting_glucose: 66.99,
    potassium: 7.88,
    sodium: 109.1,
    total_calcium: 13.78,
    total_protein: 5.85,
    creatine_unit: "mgdl",
    chloride_unit: "mmoll",
    fasting_glucose_unit: "mgdl",
    potassium_unit: "mmoll",
    sodium_unit: "ul",
    total_calcium_unit: "mgdl",
    total_protein_unit: "gdl",
  },
  {
    client_id: "d26070cc",
    date_testing: "2018-12-06",
    date_birthdate: "1950-01-01",
    gender: 1,
    ethnicity: 5,
    creatine: 1.14,
    chloride: 115.01,
    fasting_glucose: 124.68,
    potassium: 7.84,
    sodium: 148.04,
    total_calcium: 7.08,
    total_protein: 8.53,
    creatine_unit: "mgdl",
    chloride_unit: "mmoll",
    fasting_glucose_unit: "mgdl",
    potassium_unit: "mmoll",
    sodium_unit: "ul",
    total_calcium_unit: "mgdl",
    total_protein_unit: "gdl",
  },
  {
    client_id: "d26070cc",
    date_testing: "2019-06-26",
    date_birthdate: "1950-01-01",
    gender: 1,
    ethnicity: 5,
    creatine: 0.42,
    chloride: 117.13,
    fasting_glucose: 83.63,
    potassium: 4.02,
    sodium: 55.96,
    total_calcium: 12.48,
    total_protein: 8.55,
    creatine_unit: "mgdl",
    chloride_unit: "mmoll",
    fasting_glucose_unit: "mgdl",
    potassium_unit: "mmoll",
    sodium_unit: "ul",
    total_calcium_unit: "mgdl",
    total_protein_unit: "gdl",
  },
  {
    client_id: "d26070cc",
    date_testing: "2019-10-16",
    date_birthdate: "1950-01-01",
    gender: 1,
    ethnicity: 5,
    creatine: 1.29,
    chloride: 82.91,
    fasting_glucose: 62.94,
    potassium: 3.29,
    sodium: 121.97,
    total_calcium: 11.3,
    total_protein: 12.64,
    creatine_unit: "mgdl",
    chloride_unit: "mmoll",
    fasting_glucose_unit: "mgdl",
    potassium_unit: "mmoll",
    sodium_unit: "ul",
    total_calcium_unit: "mgdl",
    total_protein_unit: "gdl",
  },
  {
    client_id: "d26070cc",
    date_testing: "2019-12-29",
    date_birthdate: "1950-01-01",
    gender: 1,
    ethnicity: 5,
    creatine: 0.84,
    chloride: 114.0,
    fasting_glucose: 96.01,
    potassium: 5.64,
    sodium: 77.3,
    total_calcium: 14.55,
    total_protein: 7.5,
    creatine_unit: "mgdl",
    chloride_unit: "mmoll",
    fasting_glucose_unit: "mgdl",
    potassium_unit: "mmoll",
    sodium_unit: "ul",
    total_calcium_unit: "mgdl",
    total_protein_unit: "gdl",
  },
  {
    client_id: "d26070cc",
    date_testing: "2020-01-02",
    date_birthdate: "1950-01-01",
    gender: 1,
    ethnicity: 5,
    creatine: 0.78,
    chloride: 115.53,
    fasting_glucose: 55.32,
    potassium: 4.4,
    sodium: 75.25,
    total_calcium: 7.26,
    total_protein: 11.22,
    creatine_unit: "mgdl",
    chloride_unit: "mmoll",
    fasting_glucose_unit: "mgdl",
    potassium_unit: "mmoll",
    sodium_unit: "ul",
    total_calcium_unit: "mgdl",
    total_protein_unit: "gdl",
  },
  {
    client_id: "d26070cc",
    date_testing: "2020-01-17",
    date_birthdate: "1950-01-01",
    gender: 1,
    ethnicity: 5,
    creatine: 0.61,
    chloride: 118.64,
    fasting_glucose: 50.57,
    potassium: 1.6,
    sodium: 51.45,
    total_calcium: 7.47,
    total_protein: 5.2,
    creatine_unit: "mgdl",
    chloride_unit: "mmoll",
    fasting_glucose_unit: "mgdl",
    potassium_unit: "mmoll",
    sodium_unit: "ul",
    total_calcium_unit: "mgdl",
    total_protein_unit: "gdl",
  },
  {
    client_id: "d26070cc",
    date_testing: "2020-03-08",
    date_birthdate: "1950-01-01",
    gender: 1,
    ethnicity: 5,
    creatine: 1.01,
    chloride: 99.15,
    fasting_glucose: 137.99,
    potassium: 1.79,
    sodium: 81.51,
    total_calcium: 12.21,
    total_protein: 11.41,
    creatine_unit: "mgdl",
    chloride_unit: "mmoll",
    fasting_glucose_unit: "mgdl",
    potassium_unit: "mmoll",
    sodium_unit: "ul",
    total_calcium_unit: "mgdl",
    total_protein_unit: "gdl",
  },
];
